/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/Chicken.glb --types 
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { useRef } from 'react'
import { useFrame } from '@react-three/fiber'

type GLTFResult = GLTF & {
  nodes: {
    ['Cube035_Cube034-Mesh']: THREE.Mesh
    ['Cube035_Cube034-Mesh_1']: THREE.Mesh
    ['Cube035_Cube034-Mesh_2']: THREE.Mesh
    ['Cube035_Cube034-Mesh_3']: THREE.Mesh
    ['Cube035_Cube034-Mesh_4']: THREE.Mesh
  }
  materials: {
    FF9800: THREE.MeshStandardMaterial
    FFFFFF: THREE.MeshStandardMaterial
    ['1A1A1A']: THREE.MeshStandardMaterial
    F44336: THREE.MeshStandardMaterial
    ['455A64']: THREE.MeshStandardMaterial
  }
}

export function Chicken(props: JSX.IntrinsicElements['group']) {
  const groupRef = useRef<THREE.Group>(null);
  const { nodes, materials } = useGLTF('./models/chicken/model.glb') as GLTFResult

  useFrame(() => {
    if (!groupRef.current) return;
      
    groupRef.current.rotation.y += 0.01;
  });

  return (
    <group ref={groupRef} {...props} dispose={null}>
      <mesh geometry={nodes['Cube035_Cube034-Mesh'].geometry} material={materials.FF9800} />
      <mesh geometry={nodes['Cube035_Cube034-Mesh_1'].geometry} material={materials.FFFFFF} />
      <mesh geometry={nodes['Cube035_Cube034-Mesh_2'].geometry} material={materials['1A1A1A']} />
      <mesh geometry={nodes['Cube035_Cube034-Mesh_3'].geometry} material={materials.F44336} />
      <mesh geometry={nodes['Cube035_Cube034-Mesh_4'].geometry} material={materials['455A64']} />
    </group>
  )
}

useGLTF.preload('./models/chicken/model.glb')
