/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 --types ./public/models/grass/model.glb 
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['Node-Mesh']: THREE.Mesh
    ['Node-Mesh_1']: THREE.Mesh
  }
  materials: {
    mat9: THREE.MeshStandardMaterial
    mat10: THREE.MeshStandardMaterial
  }
}

export function Grass(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('./models/grass/model.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Node-Mesh'].geometry} material={materials.mat9} />
      <mesh geometry={nodes['Node-Mesh_1'].geometry} material={materials.mat10} />
    </group>
  )
}

useGLTF.preload('./models/grass/model.glb')
